CREATE USER adas IDENTIFIED BY adas;
GRANT CONNECT,RESOURCE TO adas;
GRANT CREATE VIEW, DROP ANY VIEW, UNDER ANY VIEW TO adas;
GRANT CREATE SYNONYM, DROP ANY SYNONYM, CREATE PUBLIC SYNONYM , DROP PUBLIC SYNONYM TO adas;
ALTER USER adas DEFAULT TABLESPACE adas_dat TEMPORARY TABLESPACE temp;

CREATE USER athena IDENTIFIED BY athena;
GRANT CONNECT,RESOURCE TO athena;
GRANT CREATE VIEW, DROP ANY VIEW, UNDER ANY VIEW TO athena;
GRANT CREATE SYNONYM, DROP ANY SYNONYM, CREATE PUBLIC SYNONYM , DROP PUBLIC SYNONYM TO athena;
ALTER USER athena DEFAULT TABLESPACE adpc_dat TEMPORARY TABLESPACE temp;

CREATE USER athena_imp IDENTIFIED BY athena;
GRANT CONNECT,RESOURCE TO athena_imp;
GRANT CREATE VIEW, DROP ANY VIEW, UNDER ANY VIEW TO athena_imp;
GRANT CREATE SYNONYM, DROP ANY SYNONYM, CREATE PUBLIC SYNONYM , DROP PUBLIC SYNONYM TO athena_imp;
ALTER USER athena_imp DEFAULT TABLESPACE adpc_dat TEMPORARY TABLESPACE temp;

CREATE USER transfer IDENTIFIED BY www;
GRANT CONNECT,RESOURCE TO transfer;
GRANT CREATE VIEW, DROP ANY VIEW, UNDER ANY VIEW TO transfer;
GRANT CREATE SYNONYM, DROP ANY SYNONYM, CREATE PUBLIC SYNONYM , DROP PUBLIC SYNONYM TO transfer;
ALTER USER transfer DEFAULT TABLESPACE adas_dat TEMPORARY TABLESPACE temp;
